### ISSUE TITLE
Limit evidence submission to mediators

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/claims-manager#10]
The claimant submits their evidence during claim creation. After that, only mediators should be able to submit additional evidence.
We can consider creating an "evidence submitter" role but it would probably be redundant. It feels like mediators should at least be able to submit evidence to justify their settlement proposal, and at that point it's probably fine to treat them as the ones representing the DAOs case.

**Comment by ErichDylus** [comment]
Agreed, this makes the most sense as the mediator is an designated interested party in the claims process and evidence submission is necessarily gated. Mediators could accept, filter, and submit evidence/information provided by third parties as relevant to the claim; the other way a non-mediator could attempt to introduce evidence or analysis into the process would be amicus curiae-like forum posts or other public methods to transparently apprise the mediators, claimant and observers

**Comment by ErichDylus** [comment]
I should also note that in traditional "mediation" a mediator wouldn't be an interested party that unilaterally introduces evidence, but they might perform some filtration as to validity of evidence introduced, so the terminology works fine for this alternative claims resolution in my opinion.

**Comment by bbenligiray** [comment]
As a note, Kleros docs is against limiting evidence submission
https://kleros.gitbook.io/docs/integrations/integrations-faq#can-should-i-prevent-new-evidence-from-being-submitted-after-a-dispute-has-been-initiated
> It is not possible to stop this from a technical perspective

does not apply in our case, and we give an opportunity to both parties to submit evidence. We're only constraining the conditions of when one can submit evidence.

**Comment by bbenligiray** [comment]
From a technical implementation POV, adding another role feels like over-engineering. If we feel the need, we can implement a proxy mediator contract that can only submit evidence and another proxy mediator contract that can only propose settlements etc. to implement more granular roles after the contract is deployed. The same approach can be used to allow anyone to submit evidence any time, if we find out that the approach above doesn't work as we expected.
