### ISSUE TITLE
Limit appeals to parties

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/claims-manager#11]
When the Kleros arbitrator decides to pay out the settlement, only the claimant should be able to appeal. When the Kleros arbitrator decides to pay out the original claim, only the DAO representation should be able to appeal. We again have the question of who this representation is (similar to https://github.com/api3dao/claims-manager/issues/10), which is probably the mediators. @ErichDylus comments?

**Comment by ErichDylus** [comment]
I agree that it would make most sense to be the mediators, and that evidence submission (as mentioned and I've commented in #10 ) is also properly limited to mediator as the interested party. Prospective appellants would need to have some sort of standing to appeal and mediators (as designated party for the relevant claim by the DAO) would be the best candidate
