### ISSUE TITLE
Add timestamp to claim creation

### ISSUE THREAD

**Issue by bbenligiray** [api3dao/claims-manager#56]

**Comment by mcoetzee** [comment]
It's the `CreatedPolicy` event that hasn't got the timestamp (the claim event already has it 👍).

**Comment by bbenligiray** [comment]
We don't show the policy creation date though, only until when claims are allowed

**Comment by mcoetzee** [comment]
Correct. Tamara asked though if we wanted to show the creation date on the Policies list, to which you replied why not, and that was when I raised that we don't have the date on the event. 

I'm not sure we need to display it either, so we can probably skip. I'm not fussed 🙂
